---
name: builder-toolbox build
on:
  push:
    branches:
    - 'main'
    - 'release/**'
    paths:
      - 'src/builder/**'
  workflow_dispatch:
    inputs:
      github-api-auth:
        type: boolean

jobs:
  builder-toolbox:
    uses: ixxeL-actions/workflows/.github/workflows/container-img-builder.yaml@main
    with:
      build-image: ${{ vars.BUILD_IMG }}
      component: builder
      workingdir: src/builder
      img-name: toolbox
      artefact: Dockerfile
      github-api-auth: true
      fail-on: critical
      cache-registry: ${{ vars.CACHE_REGISTRY }}
      podman-registry: ${{ vars.DOCKER_HUB_REGISTRY }}
      podman-username: ${{ vars.DOCKER_HUB_USER }}
      docker-hub-login: true
    secrets:
      github-api-rest-token: ${{ secrets.GH_API_TOKEN }}
      docker-io-pwd: ${{ secrets.DOCKER_IO_PWD }}
      registry-password: ${{ secrets.DOCKER_IO_PWD }}

