---
name: cd-toolbox build
on:
  push:
    branches:
    - main
    paths:
      - 'src/cd-toolbox/**'
      - '.github/workflows/cd-toolbox.yml'
  workflow_dispatch:

jobs:
  cd-toolbox:
    uses: ixxeL-actions/workflows/.github/workflows/container-img-builder.yaml@main
    with:
      workingdir: src/cd-toolbox
      format: cli
      img-name: cd-toolbox
      artefact: Dockerfile
      github-api-auth: true
      github-api-rest-token: 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
      fail-on: low
      cache-registry: docker.io/ixxel
      docker-hub-login: true
      docker-io-user: ixxel
      docker-io-pwd: 2794d8ea-0fa5-4039-8036-9bc85f3765af



    # name: Build
    # runs-on: ubuntu-20.04
    # container:
    #   image: ixxel/cd-toolbox:latest
    # steps:
    # - name: Checkout code
    #   uses: actions/checkout@v3

    # - name: Run Trivy vulnerability scanner
    #   uses: aquasecurity/trivy-action@master
    #   with:
    #     image-ref: docker.io/ixxel/ci-toolbox:latest
    #     format: table
    #     vuln-type: os,library
    #     severity: CRITICAL,HIGH
    #   env:
    #     TRIVY_USERNAME: ixxel
    #     TRIVY_PASSWORD: 2794d8ea-0fa5-4039-8036-9bc85f3765af
    # - name: Security scan for docker image (Grype)
    #   id: scan-image1
    #   uses: ixxeL-actions/grype-scan@main
    #   with:
    #     image-ref: docker.io/ixxel/ci-toolbox:latest
    #     transport: registry
    #     fail-on: '""'
    #     output: table
    #     scope: AllLayers
    #     template: '""'
    #     verbose: ''
