---
name: cd-toolbox build
on:
  push:
    branches:
    - 'main'
    - 'release/**'
    paths:
      - 'src/cd/**'
  workflow_dispatch:

jobs:
  cd-toolbox:
    uses: ixxeL-actions/workflows/.github/workflows/docker-build.yaml@main
    with:
      component: cd
      workingdir: src/cd
      img-name: toolbox
      podman-username: ${{ vars.DOCKER_HUB_USER }}
    secrets:
      git-token: ${{ secrets.PAT }}
      DOCKER_IO_PWD: ${{ secrets.DOCKER_IO_PWD }}
