---
name: ci-toolbox build
on:
  push:
    branches:
      - "main"
    paths:
      - "src/ci/**"
  pull_request:
    types:
      - opened
      - synchronize
    branches:
      - "main"
    paths:
      - "src/ci/**"
  workflow_dispatch:

jobs:
  ci-toolbox:
    uses: ixxeL-actions/workflows/.github/workflows/docker-build.yaml@main
    with:
      component: ci
      workingdir: src/ci
      img-name: toolbox
      podman-username: ${{ vars.DOCKER_HUB_USER }}
    secrets:
      git-token: ${{ secrets.PAT }}
      DOCKER_IO_PWD: ${{ secrets.DOCKER_IO_PWD }}
