name: CI
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
env:
  RED: \033[1;31m
  GREEN: \033[1;32m
  YELLOW: \033[1;33m
  BLUE: \033[1;34m
  PURPLE: \033[1;35m
  CYAN: \033[1;36m
  BLANK: \033[0m
  WORKING_DIR: resources/multi-tools
  IMAGE: multi-tools
  REPOSITORY: ixxel
  VERSION: "1.0.0"

jobs:
  test:
    strategy:
      matrix:
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}
    container: 
      image: ixxel/unit-test:v1.1
    defaults:
      run:
        shell: bash
    steps:
    - uses: actions/checkout@v2
    - name: Lint with Hadolint
      id: lint-hadolint
      run: |
        echo -e "${BLUE}[ STEP - LINTING DOCKERFILE ] > Linting ${IMAGE} Dockerfile with Hadolint.${BLANK}"
        echo -e "${CYAN}[ INFO ] > Hadolint version.${BLANK}"
        hadolint --version
        echo -e "${YELLOW}[ EXECUTING ] > Executing Dockerfile linting.${BLANK}"
        hadolint ${WORKING_DIR}/Dockerfile --ignore DL3007 --ignore DL3017 --ignore DL3018 --ignore DL4001 --ignore DL4006 --ignore DL3013

  build:
    needs: [test]
    strategy:
      matrix:
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}
    container: 
      image: ixxel/multi-tools-alpine:v1.0
      options: --privileged
    defaults:
      run:
        shell: bash
    steps:
    - uses: actions/checkout@v2
    - name: Build image version
      id: build-version
      run: |
        echo -e "${BLUE}[ STEP - BUILDING VERSION ] > Building docker image version.${BLANK}"
        echo -e "${YELLOW}[ EXECUTING ] > Executing building.${BLANK}"
        IMAGE_VERSION=${VERSION}-${{ github.run_number }}
        echo -e "${CYAN}[ INFO ] > Image version for ${IMAGE} is ${IMAGE_VERSION}.${BLANK}"