---
name: helm build
on:
  push:
    branches:
    - main
    - ^release/[0-9]+\.[0-9]+
    paths:
      - 'src/helm/**'
      - '.github/workflows/helm.yml'
  workflow_dispatch:

jobs:
  helm:
    uses: ixxeL-actions/workflows/.github/workflows/container-img-builder.yaml@main
    with:
      workingdir: src/helm
      format: cli
      img-name: helm-toolbox
      artefact: Dockerfile
      github-api-auth: true
      fail-on: low
      cache-registry: docker.io/ixxel
      docker-hub-login: true
      docker-io-user: ixxel
    secrets:
      github-api-rest-token: ${{ secrets.GH_API_TOKEN }}
      docker-io-pwd: ${{ secrets.DOCKER_IO_PWD }}

    # name: Build
    # runs-on: ubuntu-20.04
    # container:
    #   image: ixxel/certs:latest
    # steps:
    # - name: Checkout code
    #   uses: actions/checkout@v3

    # - name: Run Trivy vulnerability scanner
    #   uses: aquasecurity/trivy-action@master
    #   with:
    #     image-ref: docker.io/ixxel/ci-toolbox:latest
    #     format: table
    #     vuln-type: os,library
    #     severity: CRITICAL,HIGH
    #   env:
    #     TRIVY_USERNAME: ixxel
    #     TRIVY_PASSWORD: 2794d8ea-0fa5-4039-8036-9bc85f3765af
    # - name: Security scan for docker image (Grype)
    #   id: scan-image1
    #   uses: ixxeL-actions/grype-scan@main
    #   with:
    #     image-ref: docker.io/ixxel/ci-toolbox:latest
    #     transport: registry
    #     fail-on: '""'
    #     output: table
    #     scope: AllLayers
    #     template: '""'
    #     verbose: ''
