---
name: helm-toolbox build
on:
  push:
    branches:
    - 'main'
    - 'release/**'
    paths:
      - 'src/helm/**'
  workflow_dispatch:

jobs:
  helm:
    uses: ixxeL-actions/workflows/.github/workflows/container-img-builder.yaml@main
    with:
      component: helm
      workingdir: src/helm
      format: cli
      img-name: toolbox
      artefact: Dockerfile
      github-api-auth: true
      fail-on: low
      cache-registry: docker.io/ixxel
      podman-registry: docker.io
      podman-username: ixxel
      docker-hub-login: true
    secrets:
      github-api-rest-token: ${{ secrets.GH_API_TOKEN }}
      docker-io-pwd: ${{ secrets.DOCKER_IO_PWD }}
      registry-password: ${{ secrets.DOCKER_IO_PWD }}

